### ISSUE TITLE
[0.4.1] Unable to Add New Scene In-between in Screenplay View

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#102]
When an attempt was made to add a new scene between two already written scene (by pressing Cmd+Shift+N after placing cursor at desired location), the new scene still got appended in the end.

**Comment by teriflix** [comment]
@suryavasishta - does this still happen in 0.4.2-dev-beta?

**Comment by suryavasishta** [comment]
@teriflix Yes. Just tried. Still happening.

**Comment by pnudupa** [comment]
It has been fixed for a while. So closing.
