### ISSUE TITLE
[0.4.1] Songs placement

### ISSUE THREAD

**Issue by praveenudupa** [teriflix/scrite#103]
Indian cinemas have songs. They are big.
Need features to support the following:
- placement of song in the timeline
- ability to write lyric of the song
- ability to add sub-scenes within the song

**Comment by teriflix** [comment]
Copying over Surya's comment from #105: This is an enhancement request. When a scene is marked as song/action, the icon also needs to show up on the pull out pane on the left, and on the corresponding boxes in structure tab etc. The icon itself is most useful when the writer has a birds eye view of the script - which is exactly what happens in the scene scroll pane, and in the structure tab.
