### ISSUE TITLE
[0.4.2-dev-beta] Song/Action Icon Needs To Show Everywhere The Scene Shows Up

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#105]
This is an enhancement request. When a scene is marked as song/action, the icon also needs to show up on the pull out pane on the left, and on the corresponding boxes in structure tab etc. The icon itself is most useful when the writer has a birds eye view of the script - which is exactly what happens in the scene scroll pane, and in the structure tab.

**Comment by teriflix** [comment]
The song & action sequence is a feature that is still work in progress. We will close this ticket for now, and continue to track everything related to it under issue #103
