### ISSUE TITLE
[0.4.2-dev-beta] Scroll to Scene

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#106]
Bug - When a scene is selected on the pull out pane, the screenplay scrolls to the scene just after the slug line - i.e., the first line of the scene is at the top of the window, instead of the slug line. The scroll position needs adjusting.

**Comment by pnudupa** [comment]
@suryavasishta - can you attach a screenshot to this ticket, showcasing this? I am unable to reproduce it on my system.

**Comment by suryavasishta** [comment]
Strange. It has stopped happening!! There might be a pattern to this bug in that case. If it repeats, I will share a screenshot.

**Comment by suryavasishta** [comment]
<img width="2160" alt="Screenshot 2020-06-23 at 12 31 41 PM" src="https://user-images.githubusercontent.com/67165149/85371410-d04c6c00-b54d-11ea-9a1d-37f0a018f145.png">

This happened just now. I cannot identify the pattern, but as you can see, I selected Scene 36, and the screenplay scrolled to the correct scene, however the slug line is just outside the visible area at the top. Subsequently any other scene I selected loaded correctly.

This happened when I just opened the software. I closed and opened it again, and tried. It didn't repeat! So the pattern is still not known to be, but the error is present, hidden somewhere.

**Comment by suryavasishta** [comment]
This happened just now. I cannot identify the pattern, but as you can see, I selected Scene 36, and the screenplay scrolled to the correct scene, however the slug line is just outside the visible area at the top. Subsequently any other scene I selected loaded correctly.

This happened when I just opened the software. I closed and opened it again, and tried. It didn't repeat! So the pattern is still not known to be, but the error is present, hidden somewhere.

<img width="2160" alt="Screenshot 2020-06-23 at 12 31 41 PM" src="https://user-images.githubusercontent.com/67165149/85371964-bfe8c100-b54e-11ea-86f7-d86290457409.png">

**Comment by suryavasishta** [comment]
No clue why this is still open 🙈
Works neatly - now on Epside/Act Breaks as well!
Closing this. Apologies for not doing so much earlier.
