### ISSUE TITLE
[0.4.2-dev-beta] Open/Save Box Redesign

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#109]
Design Suggestion 01:
https://drive.google.com/file/d/1nWMGWb_fIHq7elsT5CWrH1jFLzo-v5uh/view?usp=sharing
(bottom left, above page number - non intrusive)

Design Suggestion 02:
https://drive.google.com/file/d/1MzYTCE8q5V35VWFtrJZobkmqowH_DsGM/view?usp=sharing
(minimal, and more in line with the design language of the UI)

**Comment by suryavasishta** [comment]
The edge border is still a lot 'rounder' .. can be reduced to a radius of about 3px.

**Comment by praveenudupa** [comment]
I guess Design Suggestion 02 is implemented. 
If Surya looks at this and closes it that'd be best

**Comment by praveenudupa** [comment]
Sorry...closed by mistake.
Design Suggestion 02 is implemented.
Since Surya created this issue, many be he should validate and close the issue

**Comment by pnudupa** [comment]
@prashanthudupa, yes. you are right.
@suryavasishta - can you please verify and close this issue?

**Comment by suryavasishta** [comment]
Super. Looks nice to me :)
