### ISSUE TITLE
[0.4.2] Wish to Save? Yes No Cancel

### ISSUE THREAD

**Issue by praveenudupa** [teriflix/scrite#111]
While working on a scrite file, should the user click the New button or press Ctrl+N, an option comes up asking if the user wishes to save the current scrite file. Here there are Yes and No options only. May be a Cancel option is required here. 

Clicking the Cancel (or may be Escape) should allow the user to go back to working on the current scrite file.

**Comment by pnudupa** [comment]
<img width="573" alt="Screenshot 2020-06-28 at 4 47 37 PM" src="https://user-images.githubusercontent.com/8263701/85946002-1bf08280-b95f-11ea-8483-f857897e6015.png">

Fixed.

**Comment by praveenudupa** [comment]
When you close Scrite App by clicking the X button, Yes, No are the only options. Cancel isn't available there
<img width="517" alt="Screenshot 2020-07-03 at 10 15 22 PM" src="https://user-images.githubusercontent.com/63054504/86487070-b9dab780-bd7a-11ea-9827-887b5febcdeb.png">

**Comment by teriflix** [comment]
@praveenudupa - 0.4.5 Beta now shows Cancel during window-close also.
