### ISSUE TITLE
[0.4.3] Provide a setting to configure dialogues in a specific language

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#112]
Can you allow font preference while configuring the Elements? Right now your software allows setting font size, line height etc. for an element. How about letting the user configure the Font choice also right there? In this case a writer like me who writes his action in English and dialogue in Hindi/Marathi can set the font of the dialogue as Hindi so whenever I go to write the dialogue automatically Hindi devnagri font is selected and I don't have to choose/change the font every time.

**Comment by pnudupa** [comment]
<img width="1440" alt="paragraph-language" src="https://user-images.githubusercontent.com/8263701/85951058-44d44000-b97e-11ea-9d6c-c6cbf22eeb03.png">

Paragraph format in the settings dialog box now sports a language setting.
