### ISSUE TITLE
[0.4.3] Add support for Marathi language

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#114]
"But I see Marathi is also absent which can be added easily. It's also significant given the quantity of small budget films that are produced in Marathi. Moreover as of now there is no S/w which can help with Marathi script. It's also important because Marathi people aren't fluent with English or don't prefer it and eventually write in unorganized way in Word. Though it looks like Hindi script there are a lot of special letters and style different from Hindi." - Note from Sanjay Sharma, Writer.

**Comment by pnudupa** [comment]
Added as of 0.5.2 https://www.scrite.io/index.php/marathi-support/
