### ISSUE TITLE
OK - Cancel - Restore Default options in Settings dialog

### ISSUE THREAD

**Issue by praveenudupa** [teriflix/scrite#119]
When a user makes changes to Settings, it would probably be good (at least for Windows users) to have:

- **OK** button - instead of closing the Settings dialog using the x button, an OK button would be good, isn't it?
- **Cancel** button - to cancel all changes made in this instance (i.e. after launching settings dialog in this instance)
- **Restore Defaults** button - to, well...restore defaults.

**Comment by teriflix** [comment]
@praveenudupa  - Since we have chosen to have a "Apply Only" dialog box, we can perhaps close this ticket.

**Comment by praveenudupa** [comment]
OK is the tick mark on the top right corner
Cancel is the Escape button
Restore Defaults is now added
