### ISSUE TITLE
[0.4.4] Reordering 'Open' Menu

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#122]
Not sure if this is a bug or enhancement; Might make more sense to flip the order of this menu. It makes sense that 'Recent Files' flyout is the first option, and when the user wants to open something not in Recent Files, he would choose 'Open Another'.

**Comment by teriflix** [comment]
@suryavasishta - I would prefer Open option to be first, but it does make sense to show recent files in the open-menu itself instead of in another submenu. That's now been implemented in 0.4.5 Beta. Hope we can close this ticket.
