### ISSUE TITLE
[0.4.4] Structure Tab Allocation of Scene Nos. Not in Order

### ISSUE THREAD

**Issue by suryavasishta** [teriflix/scrite#123]
Couldn't make sense of this when I went to the structure tab. In screenplay view, I've written 55 scenes. In structure view, post scene 50, the numbers go 52, 53, 54, 59, 56, 58 ..

<img width="2160" alt="Screenshot 2020-06-29 at 6 54 35 PM" src="https://user-images.githubusercontent.com/67165149/86011632-8f1af700-ba3a-11ea-987b-e66e61be7003.png">

**Comment by teriflix** [comment]
This is not a bug. The text shown in the boxes are not scene numbers. They are just about any text you have on the structure boxes. When you first import a screenplay from another source (like Final Draft, Celtx etc..); the boxes are given a "one line description" which includes a scene number in chronological order as they appear in the source screenplay. But you can double click on the box and give it any text of your choice, with or without scene numbers. We don't assign scene numbers in this view. Its only in the screenplay editor that we assign scene numbers.
