### ISSUE TITLE
[0.4.8] Scene Synopsis Report

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#155]
It would be great if scene scene synopsis report can be obtained seperately.

**Comment by pnudupa** [comment]
![synopsis-report](https://user-images.githubusercontent.com/8263701/87922323-716d0a80-ca99-11ea-8bea-526514c98b8e.jpg)

From 0.4.11 onwards, users can uncheck "Include Scene Content" along with checking "Include Scene Synopsis" to get a synopsis only dump of screenplays. These control knobs will be available both on Reports and Exports configuration dialog box.
