### ISSUE TITLE
[0.4.12] When a dialogue block is broken into two (because of MORE-CONTD), paragraph font changes.

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#156]
Reported by Kiran Hemmige: "when exporting as a PDF, have noticed that the Kannada fonts seem to change (not sure if it is because of the “Copy-Paste” functionality or due to the “MORE & CONTD.” feature when the dialogue begins on a new page after ONLY the CHARACTER name is accommodated at the end of the previous page."

**Comment by pnudupa** [comment]
I am able to reproduce this issue. This is a bug.
