### ISSUE TITLE
[0.4.13] Get report for all INT scenes or all DAY scenes

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#158]
It should be possible for users to filter all scenes that happened during DAY, NIGHT etc and generate a report.

Similarly, filter by INT or EXT also.

**Comment by pnudupa** [comment]
<img width="829" alt="Screenshot 2020-08-07 at 5 02 05 PM" src="https://user-images.githubusercontent.com/8263701/89641655-ca2d0780-d8cf-11ea-941a-98253821a905.png">

The Screenplay Subset Report will provide (from 0.4.14 onwards) a way to filter from the 3 parts of a scene heading. Once filtered, user can manually select a further subset of click on the "Select All" button. Number of selected scenes will be reported in the status text below.
