### ISSUE TITLE
[0.4.15 Mac] Generating the "Character Report" doesn't open the folder for the exported files

### ISSUE THREAD

**Issue by HamsaNandini** [teriflix/scrite#162]
This happens only when no characters are selected before clicking on the Generate button.

**Comment by pnudupa** [comment]
This should have ideally reported an error stating "No characters were selected to generate the report."

**Comment by pnudupa** [comment]
<img width="1047" alt="report-error" src="https://user-images.githubusercontent.com/8263701/91744182-b165f800-ebd6-11ea-9de7-975e4d964e04.png">

We now show this error message.

**Comment by HamsaNandini** [comment]
Retested on [0.4.17 Mac] , issue is fixed. Character Report opens as expected.
Closing the bug
