### ISSUE TITLE
[0.6.4 All] Scene numbers not included in ODT export, even if explicitly checked.

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#218]
Bug reported by: Harish Narayan

1. Open Punyakoti from Scriptalay

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63646106/117561455-a4c66780-b0b4-11eb-97a5-14d466698178.png">

2. Select Export -> Open Document Format

<img width="476" alt="image" src="https://user-images.githubusercontent.com/63646106/117561460-b27bed00-b0b4-11eb-96de-c7df70c34f39.png">

3. Check "Include Scene Numbers" and "Include Scene Synopsis"

<img width="489" alt="image" src="https://user-images.githubusercontent.com/63646106/117561483-ddfed780-b0b4-11eb-8f2a-5f1d19fb5360.png">

4. Export the screenplay to ODT and open it in LibreOffice, OpenOffice or Microsoft Word.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/63646106/117561498-f969e280-b0b4-11eb-89ae-7750768c2772.png">

Notice that scene numbers are not included in the exported file.

**Comment by pnudupa** [comment]
This is now fixed.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/8263701/117561574-9a589d80-b0b5-11eb-967b-6a973fed1f0c.png">

We can't export a ODT file with scene number in the left margin. So we simply prefix scene headings with the scene number.

**Comment by pnudupa** [comment]
We now also allow scene numbers to be included in ODT reports for Character, Location and Scene subset reports.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/8263701/117561887-4307fc80-b0b8-11eb-8363-f77f68bd0938.png">

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8263701/117561897-57e49000-b0b8-11eb-8f46-2e543db465e7.png">

**Comment by teriflix** [comment]
Harish confirmed that the bug is indeed fixed in 0.6.5b nightly build.
