### ISSUE TITLE
[0.6.4 All] When app is launched instead of showing an empty document, it shows a modified document

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#219]
<img width="156" alt="image" src="https://user-images.githubusercontent.com/63646106/117561550-69786880-b0b5-11eb-8c8a-0a7c694b1a56.png">

App launches to a modified document.

**Comment by pnudupa** [comment]
This looks like a regression caused due to  #211. The problem surfaces only when user has saved default values for certain fields in title page.
