### ISSUE TITLE
[0.6.4 All] Half the text inside the logline widget is hidden

### ISSUE THREAD

**Issue by ghoomfrog** [teriflix/scrite#221]
![Cropped screenshot of the logline widget](https://i.ibb.co/BTgHMHq/scrite-bug1.png)

**Comment by pnudupa** [comment]
Yeah, this seems to happen when the zoom level is less than 100. Nevertheless, its a valid issue. Thanks for opening a ticket.

**Comment by teriflix** [comment]
Addressed in 0.6.6
