### ISSUE TITLE
[0.6.4 All] No built-in shortcut to exit the program

### ISSUE THREAD

**Issue by ghoomfrog** [teriflix/scrite#223]
Usually `Ctrl-Q`.

**Comment by pnudupa** [comment]
Alt+F4 on Windows, Command+Q on macOS. Why reinvent this, when every OS has its standard shortcuts for closing the current app.

**Comment by ghoomfrog** [comment]
> Alt+F4 on Windows, Command+Q on macOS. Why reinvent this, when every OS has its standard shortcuts for closing the current app.

It just seems odd.

**Comment by pnudupa** [comment]
No its not. Its odd that every app finds it an obligation to add a quit option when the OS provides one for free.
