### ISSUE TITLE
[0.6.4 All] Why is the fullscreen shortcut F7 and not F11?

### ISSUE THREAD

**Issue by ghoomfrog** [teriflix/scrite#228]

**Comment by pnudupa** [comment]
F11 on Mac reveals the desktop. The intention is to keep shortcuts consistent across platforms. F7 seemed like a good option.

**Comment by ghoomfrog** [comment]
> F11 on Mac reveals the desktop. The intention is to keep shortcuts consistent across platforms. F7 seemed like a good option.

Of course Mac would do that. *facepalm*

**Comment by pnudupa** [comment]
@Unlimiter: Perhaps we should simply provide a way for users to to map/change keyboard shortcuts for all user actions in Scrite. That way each user can configure Scrite to their own comfort.

**Comment by ghoomfrog** [comment]
@pnudupa Definitely!
