### ISSUE TITLE
[0.6.4 Linux] The "Pull this handle to view the screenplay editor" message always pops up

### ISSUE THREAD

**Issue by ghoomfrog** [teriflix/scrite#229]

**Comment by pnudupa** [comment]
Thanks for filing this. The next nightly build should have addressed this. If you are building from the code, then please pull from 0.6.5 branch and check once. Otherwise, I will update this ticket when the next nightly build is uploaded.

**Comment by pnudupa** [comment]
@Unlimiter: Try out the latest nightly build https://www.scrite.io/index.php/downloads/#nightly_builds

**Comment by ghoomfrog** [comment]
@pnudupa I tried it and the message no longer pops up.

**Comment by ghoomfrog** [comment]
@pnudupa I've tested things more. And the message pops up whenever I open my document (at the Structure tab).

**Comment by pnudupa** [comment]
@Unlimiter - yes, it should show up once per document. Not every time the user switches to the structure tab after opening the document.

**Comment by ghoomfrog** [comment]
@pnudupa No. It shows up whenever I open the same document.

**Comment by teriflix** [comment]
Yes, that's the intention. To show the animation once each time the document is opened. If you save the document with editor and timeline panels expanded, then the animation is not shown.

**Comment by ghoomfrog** [comment]
@teriflix But what if I don't want to open the panel at all? That's annoying.

**Comment by teriflix** [comment]
Sorry, if it's annoying. We are not developing the product to make it not annoying for you. It's something a bunch of our users feel the need for. So we are going to keep it.

**Comment by teriflix** [comment]
Between users forgetting that they need to pull the handles to reveal the editor and timeline areas, and finding this animation annoying; right now it's inclining towards the former.

A feature doesn't become a bug because you find it annoying. 

If other users, primarily writers, also complain we are happy to rework it.

Once again, please open tickets here only if it's a bug. For everything else use the Forum.

**Comment by ghoomfrog** [comment]
@teriflix I'm pretty sure no one wants to be bothered by a message every single time they open the same document.

**Comment by pnudupa** [comment]
@Unlimiter - okay, just for you we now have this..

![image](https://user-images.githubusercontent.com/8263701/118496135-79411e00-b741-11eb-9a93-5a9e11f08233.png)

**Comment by ghoomfrog** [comment]
@pnudupa Yay! BTW, the Nightly Builds folder on OneDrive is empty. Where can I get them now?

**Comment by ghoomfrog** [comment]
Never mind.
