### ISSUE TITLE
[0.6.5 Linux] Inconsistent capitalization (see the images for clarification)

### ISSUE THREAD

**Issue by ghoomfrog** [teriflix/scrite#235]
![](https://i.ibb.co/PN70vYq/scrite-bug5-1.png)
![](https://i.ibb.co/0KZgNH8/scrite-bug5-2.png)
As you can see. I've set the name to be "Hero's Journey" in the settings. But it doesn't translate correctly to the one on the card.

**Comment by pnudupa** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/8263701/118389915-f5f0d100-b649-11eb-98d0-1b1da8221778.png">

Fixed this.
