### ISSUE TITLE
[0.6.6 All] Provide ability to generate Acts from a new page.

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#236]
Currently episodes get a page break, but acts don't. It would be useful if there was an option to allow acts to start from a new page, with a heading.

**Comment by pnudupa** [comment]
![image](https://user-images.githubusercontent.com/8263701/119959138-558f9a80-bfc1-11eb-838e-288680247650.png)

By checking "Print each act on a new page", the generated PDF file will insert a page break for every act and also include act names in the generated PDF.

By checking "Include act break", the generated PDF will include act breaks (without breaking pages) along with the other screenplay content.
