### ISSUE TITLE
[0.6.6 All] Mark Scene As could show icons for scene types.

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#238]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/63646106/119937128-dc377e00-bfa7-11eb-9af5-1f9e6d13a924.png">

In the absence of icons on this menu, it is difficult to correlate icons to their type when they do show up on the scene or index card.

**Comment by pnudupa** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/8263701/120018424-c4421780-c004-11eb-9e10-ac78348bd3af.png">

We show icons on the menu now.
