### ISSUE TITLE
[0.6.6 All] Provide a way to explicitly request for title page fields to be saved as default

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#239]
Currently whenever the user changes anything on the title page field, the values are used as defaults for future documents. Probably a good idea to explicitly check an option requesting for it to be saved as default fields.

**Comment by pnudupa** [comment]
![image](https://user-images.githubusercontent.com/8263701/120020861-ee490900-c007-11eb-9a8d-ad16c7d27069.png)

Users will now have to click a button to save title page fields as default.
