### ISSUE TITLE
[0.6.8 All] Unable to remove notebook section

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#249]
Ref: https://www.scrite.io/index.php/forum/topic/remove-section-not-working/

![image](https://user-images.githubusercontent.com/63646106/123988133-60d14e00-d9e5-11eb-98c4-48cde2470173.png)

The remove option doesn't work.

**Comment by pnudupa** [comment]
Since we have completely changed the notebook UI, this ticket is not valid anymore. 

Besides, in the new UI - users can delete notes & characters.
