### ISSUE TITLE
[0.7.5] Auto complete doesnt work for INT/EXT and time field in scene heading

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#264]

**Comment by pnudupa** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/8263701/129439728-22aec897-15fb-418f-aa8c-dbeea6e48a74.png">

<img width="267" alt="image" src="https://user-images.githubusercontent.com/8263701/129439740-1e192375-1f90-4f9a-b343-4aa9f0f25c76.png">

We now show completion popup for these fields.
