### ISSUE TITLE
[0.7.7 All] Provide a 'Remove From Timeline' Option On The Context Menu Of An Index Card In Structure Canvas

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#270]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/63646106/130900586-7bbe9db1-11bf-4f4d-a970-17972479d1c4.png">

The menu option may be shown right next to 'Add To Timeline' and can be enabled only if its already added to the timeline.

**Comment by pnudupa** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/8263701/130907274-c0fdcf9c-52f2-43f2-9074-6488e3740aed.png">

We now show a "Remove From Timeline" option, which when clicked removes the scene from the timeline.

If the scene has not yet been added to the timeline, then the remove option will show up disabled.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/8263701/130907410-c6797310-909d-4c15-a225-8b650930fb51.png">
