### ISSUE TITLE
[0.8.8 - beta - x64] Scrolling issue while typing long dialogues/actions

### ISSUE THREAD

**Issue by gouthampkanade** [teriflix/scrite#279]
When typing long dialogues or actions, if the cursor goes below the screen, the window does not scroll down automatically. We need to either scroll down using mouse or press Page Down key to keep the visibility of the dialogue/action being written.

**Comment by teriflix** [comment]
https://www.scrite.io/index.php/0-9-beta-is-now-out/#chapter3_bug_fixes
