### ISSUE TITLE
Any option for custom formatting some text?

### ISSUE THREAD

**Issue by gouthampkanade** [teriflix/scrite#280]
I would like to highlight certain words/lines in the dialogues to indicate where there needs to be more stress, or some color highlight to indicate that they are flashback scenes, but I don't see any option to do this other than adding comments as parenthesis. You can add an enhancement to add custom formatting to selected text.

**Comment by teriflix** [comment]
https://www.scrite.io/index.php/0-9-beta-is-now-out/#chapter1_2_bold,_italics_and_underline_in_screenplay
