### ISSUE TITLE
[URGENT] Error registering email 

### ISSUE THREAD

**Issue by jas-ells** [teriflix/scrite#283]
Hello! All good? I'm trying to register on the app but the following error appears: "UnknownNetworkError: TLS initialization failed" . Can anyone help me solve this problem? Thank you very much in advance.

**Comment by teriflix** [comment]
https://www.scrite.io/index.php/using-scrite-on-linux/#chapter3_openssl

**Comment by jas-ells** [comment]
Thanks!
