### ISSUE TITLE
[0.2.4] Shortcut for Redo on Mac has to be Ctrl+Shift+Z

### ISSUE THREAD

**Issue by pnudupa** [teriflix/scrite#36]

**Comment by JimmyCushnie** [comment]
Hey, any chance we could get this on Windows as well? I hate ctrl+Y haha

It would be even better if the user could customize all keyboard shortcuts from a config file.

**Comment by pnudupa** [comment]
@JimmyCushnie: Yes, this was recently discussed against another ticket also. https://github.com/teriflix/scrite/issues/228#issuecomment-841622862

It's a good idea to provide a way to customise shortcuts. Sure want to queue this in for a future update. 👍🏻
