### ISSUE TITLE
[0.2.6] Color of the structure canvas, gird and its visibilty must be customisable

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#39]
It should be possible to customize the color of the canvas in structure tab. Would be useful to customize colors of the grid lines also, maybe even turn off the grid.

**Comment by pnudupa** [comment]
<img width="753" alt="Screenshot 2020-04-15 at 7 10 04 PM" src="https://user-images.githubusercontent.com/8263701/79343934-b8081180-7f4c-11ea-9ba2-edbdb42dced8.png">

Added a group box in the settings dialog box for configuring the grid.

**Comment by pnudupa** [comment]
<img width="753" alt="Screenshot 2020-04-15 at 7 11 41 PM" src="https://user-images.githubusercontent.com/8263701/79344083-f43b7200-7f4c-11ea-88dc-f5c125cd860c.png">

Grid color, background color can be configured.

<img width="750" alt="Screenshot 2020-04-15 at 7 12 15 PM" src="https://user-images.githubusercontent.com/8263701/79344125-05847e80-7f4d-11ea-9c3e-a6753381cb71.png">

The grid can be turned off entirely also.
