### ISSUE TITLE
[0.2.6] Provide ability to customize headers and footers of generated PDF files

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#43]
Currently the app prints page numbers on the bottom right corner. Standard screenplays show them on the top right. Additionally it must be possible for users to print their own name, contact info on the headers and footers.

**Comment by pnudupa** [comment]
<img width="749" alt="Screenshot 2020-04-16 at 2 43 20 PM" src="https://user-images.githubusercontent.com/8263701/79438027-9f513780-7ff0-11ea-9835-777c131caaff.png">

We can now configure headers & footers in generated PDF files.
