### ISSUE TITLE
[0.2.8] Undo transliterates entire scene and jumbles up text

### ISSUE THREAD

**Issue by teriflix** [teriflix/scrite#49]
This issue was reported by a user of Scrite, Mr. Karthik Rao. Steps to reproduce

1. Create a scene in English
2. Change language to Kannada
3. Type some text in Kannada
4. Undo (Ctrl+Z)
5. The entire scene text transliterates to Kannada and the text appears jumbled up.

<img width="501" alt="Screenshot 2020-04-18 at 4 02 56 PM" src="https://user-images.githubusercontent.com/63646106/79635364-13751200-818e-11ea-94c4-902972ee062a.png">

**Comment by pnudupa** [comment]
The entire Undo / Redo mechanism for scene text has to be rethought. The code runs into invalid objects a lot.

**Comment by pnudupa** [comment]
Commit 85e8a7fced9fad09a6bda5038da76612e5aed0cb makes Undo/Redo a lot more stable than before. I have disabled undo/redo of structure element creation. Otherwise, other things work.
