### ISSUE TITLE
[0.3.3] Unable to delete Act breaks in timeline

### ISSUE THREAD

**Issue by sutharsanank** [teriflix/scrite#77]
The " Add a CHaracter, Chapter , interval Break" has a Bug I guess. Its tought to use that button.
ANd Moreover I am not able to delete the ACT I, or ACT II , or ACT II etc,  in that Timeline panel

**Comment by pnudupa** [comment]
<img width="364" alt="Screenshot 2020-05-17 at 9 09 20 AM" src="https://user-images.githubusercontent.com/8263701/82135244-1a8b5080-981e-11ea-8754-c2a166bcaaad.png">

The app now displays context menus for act breaks.

**Comment by sutharsanank** [comment]
Tq so much
