### ISSUE TITLE
[0.3.3] Copy / paste an entire scene

### ISSUE THREAD

**Issue by sutharsanank** [teriflix/scrite#78]
1.Iam not able to copy the entire scene ( including Dialogue , characters, transitions) and paste it again below to rework the scene for Loop Sequence in the movie.
In case if I edit the it also changes its source as well

2. If we copy the Entire scene and paste it again , its not copied as the same format.

The only possible action to copy a scene  i drag drop the entire scene and from the structure menu to time line menu.. EVen in that too as i said before if i change the edited version it also changes the source material ..

**Comment by pnudupa** [comment]
![duplicate_a_scene](https://user-images.githubusercontent.com/63646106/82135213-a81a7080-981d-11ea-8720-cc399cc4f6f9.jpg)

Users will be able to duplicate a scene from the context menu

**Comment by sutharsanank** [comment]
TQ so much
