### ISSUE TITLE
[0.1.2] Dangling connectors upon closing a project

### ISSUE THREAD

**Issue by abhayaftii** [teriflix/scrite#8]
Steps to reproduce:
1. Open a project with lot of elements in a screenplay
2. Ensure that the structure canvas has scenes and connector lines
3. Click on the new button in the toolbar to open a new project
4. Notice dangling connectors in the canvas.

<img width="170" alt="Screenshot 2020-03-31 at 7 39 57 AM" src="https://user-images.githubusercontent.com/62919827/77979909-89225680-7323-11ea-8217-a2b7ab5daf65.png">

**Comment by pnudupa** [comment]
Fixed in 1c9ed91434767ea2912fe405ec42cc4e73e6fa3e
