### ISSUE TITLE
[0.4.1] Undo-Redo Crash

### ISSUE THREAD

**Issue by praveenudupa** [teriflix/scrite#97]
V 0.4.1

Scrite crashes upon Undo - Redo (in one instance)
Crashed again upon Undo - Redo - Enter (in another instance)

**Comment by pnudupa** [comment]
This happens when the following is true.
1. We have just begun typing a new paragraph.
2. Undo deletes all text from the new paragraph.
3. We switch focus to another window (Alt+Tab)
4. We switch back to Scrite window.
